### ISSUE TITLE
Switch translatewiki.net to use this repo

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticCompoundQueries#1]
And away from Gerrit.

Ping @kghbln @siebrand @Nikerabbit

**Comment by JeroenDeDauw** [comment]
FYI: The Gerrit copy of the repo now just holds a redirect notice to this one.

**Comment by PeterTheOne** [comment]
Is this done? Since the gerrit repository is gone.

**Comment by kghbln** [comment]
> Is this done?

Not yet. I am sure that either @Nikerabbit @siebrand or @Raimond will get around doing this sooner than later.

**Comment by Nikerabbit** [comment]
This request is on my queue for next week when I am back from vacation.

**Comment by kghbln** [comment]
> This request is on my queue for next week when I am back from vacation.

Thanks for the info. Enjoy your time off!

**Comment by Nikerabbit** [comment]
https://gerrit.wikimedia.org/r/298920

**Comment by kghbln** [comment]
Thanks!
