### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by PeterTheOne** [SemanticMediaWiki/SemanticCompoundQueries#20]
let's do a release.. :)

**Comment by JeroenDeDauw** [comment]
Fine from my end. And I'd go with 1.0 as clearly this thing is ready for use in production (http://semver.org/)

**Comment by kghbln** [comment]
> And I'd go with 1.0

:+1:

**Comment by kghbln** [comment]
@JeroenDeDauw What about a tweet?

**Comment by JeroenDeDauw** [comment]
Eh, already taken care off by my past self https://twitter.com/SemanticMW/status/778501616412405761 :)

**Comment by kghbln** [comment]
> Eh, already taken care off by my past self

Ah, so it is now up to me to like all of this. ;) Also [fluffed the docu](https://www.mediawiki.org/w/index.php?title=Extension%3ASemantic_Compound_Queries&action=historysubmit&type=revision&diff=2243013&oldid=2181339)
