### ISSUE TITLE
Can I join two categories in one subquery?

### ISSUE THREAD

**Issue by jpRsah** [SemanticMediaWiki/SemanticCompoundQueries#53]
### Setup and configuration

- SMW version: "3.1.5"
- SCQ version: "2.1.0",
- MW version: 1.34
- DB (MySQL etc.):MySQL

### Issue

Need a help with compound_query.

Can I join two categories in one subquery?

I tried this

```
{{
#compound_query:
| [[Category:Category1 Category2]] <--!!
 ;limit=5000
 ;?Has coordinates
 ;icon=Yellow_marker.png
|format=leaflet 
|zoom=2
|markercluster=on
|clustermaxzoom=7
|clusterminsize=4
|fullscreen=1
|height=400px
}}
```

**Comment by akuckartz** [comment]
"Categoty", not "Category" ?!

**Comment by kghbln** [comment]
For your example you do not need a compound query since you are not trying to join the results of two different queries. `#ask` should do here. 

I believe you can do it like in the second query down here. `OR` should work for the `#compound_query` parser function, too. If not this would be a feature request.

```
{{#compound_query:
 [[Category:Category0]]
 ;?Has coordinates
 ;limit=5000
 ;icon=Blue_marker.png
 |
 [[Category:Category1]]
 OR
 [[Category:Category2]]
 ;?Has coordinates
 ;limit=5000
 ;icon=Yellow_marker.png
 |format=leaflet 
 |zoom=2
 |markercluster=on
 |clustermaxzoom=7
 |clusterminsize=4
 |fullscreen=1
 |height=400px
 |limit=5000
}}
```

**Comment by jamesmontalvo3** [comment]
Concur, compound queries not required. You can join two categories with a regular ask:

```
{{#ask: [[Category:Cat1 || Cat2]] 
| format = ul
}}
```
