### ISSUE TITLE
Not (official) compatible with SMW 4

### ISSUE THREAD

**Issue by WouterRademaker** [SemanticMediaWiki/SemanticCompoundQueries#55]
### Setup and configuration

- SMW version: 3.2.3 / 4.0.0
- SCQ version: 2.1.0
- MW version: 1.36
- DB (MySQL etc.): 10.3.32-MariaDB-0ubuntu0.20.04.1

### Issue
changing composer.local.json to

        "require": {
                "mediawiki/semantic-media-wiki": "~4.0",
                "mediawiki/semantic-compound-queries": "*",
        },

Gives these errors when running composer update

  Problem 1
    - mediawiki/semantic-compound-queries[1.0.0, ..., 1.0.1] require mediawiki/semantic-media-wiki ~2.3 -> found mediawiki/semantic-media-wiki[2.3.0, ..., 2.5.8] but it conflicts with your root composer.json require (~4.0).
    - mediawiki/semantic-compound-queries 1.1.0 requires mediawiki/semantic-media-wiki ~2.4 -> found mediawiki/semantic-media-wiki[2.4.0, ..., 2.5.8] but it conflicts with your root composer.json require (~4.0).
    - mediawiki/semantic-compound-queries 1.2.0 requires mediawiki/semantic-media-wiki ~2.5|~3.0 -> found mediawiki/semantic-media-wiki[2.5.0, ..., 2.5.8, 3.0.0, ..., 3.2.3] but it conflicts with your root composer.json require (~4.0).
    - mediawiki/semantic-compound-queries[2.0.0, ..., 2.1.0] require mediawiki/semantic-media-wiki ~3.0 -> found mediawiki/semantic-media-wiki[3.0.0, ..., 3.2.3] but it conflicts with your root composer.json require (~4.0).
    - Root composer.json requires mediawiki/semantic-compound-queries * -> satisfiable by mediawiki/semantic-compound-queries[1.0.0, 1.0.1, 1.1.0, 1.2.0, 2.0.0, 2.1.0].

**Comment by kghbln** [comment]
SMW 4.0.0 added with this commit: 94e813b977bca46249c7f7a1959b02ce462bc449 Could you do a field test please?

**Comment by JeroenDeDauw** [comment]
You can't field test that unless you force install the master version of this extension. We need to do a release first.

**Comment by kghbln** [comment]
Huu, it is not possible to add dev-master to composer.local.json?

**Comment by WouterRademaker** [comment]
> Huu, it is not possible to add dev-master to composer.local.json to test? Not sure if I understand your comment.

That has some weird side effects like composer tries to downgrade mediawiki/page-forms (5.3.4) to  mediawiki/semantic-forms (3.7)

Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 5 updates, 5 removals
  - Removing elasticsearch/elasticsearch (v6.8.2)
  - Removing ezimuel/guzzlestreams (3.0.1)
  - Removing ezimuel/ringphp (1.2.0)
  - Removing nicmart/tree (v0.2.7)
  - Removing react/promise (v2.8.0)
  - Upgrading mediawiki/semantic-compound-queries (2.1.0 => dev-master 94e813b)
  - Locking mediawiki/semantic-forms (3.7)
  - Downgrading mediawiki/semantic-forms-select (3.0.0 => 1.3)
  - Upgrading mediawiki/semantic-media-wiki (3.2.3 => 4.0.0)
  - Downgrading mediawiki/semantic-result-formats (3.2.0 => 1.9.0.1)
  - Upgrading symfony/css-selector (v3.4.47 => v5.4.2)
Writing lock file
Installing dependencies from lock file
Package operations: 1 install, 5 updates, 5 removals
  - Downloading mediawiki/semantic-forms (3.7)

**Comment by kghbln** [comment]
> That has some weird side effects like composer tries to downgrade mediawiki/page-forms (5.3.4) to mediawiki/semantic-forms (3.7)

Ah had this too once. Would be good to track down the issue for this... Anyhow. Will do a new release of this extension to allow us to move forward. If it is broken for SMW 4.0 we need a fix anyways.

**Comment by WouterRademaker** [comment]
The problem is most likely in semantic-forms-select:
in its v1.3 composer.json:
		"mediawiki/semantic-media-wiki": ">=2.0",
		"mediawiki/semantic-forms": ">=2.7"

**Comment by kghbln** [comment]
Looks like it. Sadly this extension is basically abandoned.
