### ISSUE TITLE
composer v2 support 

### ISSUE THREAD

**Issue by markus-96** [SemanticMediaWiki/SemanticCompoundQueries#59]
### Setup and configuration

- SMW version: 4.1.1
- SCQ version: 2.2.0
- MW version: 1.39.0
- DB (MySQL etc.): mariadb

### Issue

I want to install with composer, but this extension requires composer >=1.0.1 and many other extensions do not support this anymore, for example external-data:

Produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and outputs:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - composer/installers v1.0.22 requires composer-plugin-api 1.0.0 -> found composer-plugin-api[2.3.0] but it does not match the constraint.
    - composer/installers[v1.0.23, ..., v1.8.0] require composer-plugin-api ^1.0 -> found composer-plugin-api[2.3.0] but it does not match the constraint.
    - Root composer.json requires mediawiki/external-data dev-REL1_39 -> satisfiable by mediawiki/external-data[dev-REL1_39].
    - mediawiki/semantic-compound-queries 2.2.0 requires composer/installers 1.*,>=1.0.1 -> satisfiable by composer/installers[v1.0.1, ..., v1.12.0].
    - You can only install one version of a package, so only one of these can be installed: composer/installers[v1.0.0, ..., v1.12.0, v2.2.0].
    - mediawiki/external-data dev-REL1_39 requires composer/installers ~2.1 -> satisfiable by composer/installers[v2.1.0, v2.1.1, v2.2.0].
    - Root composer.json requires mediawiki/semantic-compound-queries ~2.2 -> satisfiable by mediawiki/semantic-compound-queries[2.2.0].
```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

**Comment by markus-96** [comment]
This can be resolved by changing the requirements in `composer.json`, like in semantic-mediawiki:
```
"require": {
	"php": ">=7.3",
	"composer/installers": "^2.2.0|^1.0.1",
	"mediawiki/semantic-media-wiki": "~3.0|~4.0"
},
```

**Comment by krabina** [comment]
see https://github.com/SemanticMediaWiki/SemanticCompoundQueries/pull/58

**Comment by paladox** [comment]
I think https://github.com/SemanticMediaWiki/SemanticCompoundQueries/commit/99ffb574f6b9fb5900e92271fe2dc2ce15927d0d fixes this?
